[package]
name = "belfast-wasm"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
belfast.workspace = true
js-sys.workspace = true
naga.workspace = true
serde.workspace = true
serde-wasm-bindgen.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = [
    "AddEventListenerOptions",
    "Element",
    "Event",
    "EventTarget",
    "HtmlCanvasElement",
    "HtmlElement",
    "ImageBitmap",
    "PointerEvent",
    "WheelEvent",
    "Window",
] }
wgpu.workspace = true
