[workspace]
members = [
  "crates/belfast",
  "crates/belfast-wasm",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "ISC"
repository = "https://github.com/yiwenl/belfast"

[workspace.dependencies]
belfast = { path = "crates/belfast" }
bytemuck = { version = "1.25", features = ["derive"] }
glam = "0.30"
thiserror = "2"
wgpu = "29.0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
naga = { version = "29.0.1", features = ["wgsl-in"] }
pollster = "0.4"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
web-sys = "0.3"
winit = "0.30"
