import "../scss/global.scss";

import { GL, GLTool, GLShader, Mesh } from "../../src/alfrid";
import { vec3 } from "gl-matrix";
const canvas1 = document.createElement("canvas");
const canvas2 = document.createElement("canvas");

GL.init(canvas1);
GL.setSize(window.innerWidth / 2, window.innerHeight);

const contextLostTest = false;
if (contextLostTest) {
  GL.on(GL.CONTEXT_LOST, () => {
    console.log("WebGL Context Lost");
  });

  setTimeout(() => {
    console.log("Destroy context");
    GL.destroy();
  }, 2000);
}

const GL2 = new GLTool();
const ctx2 = canvas2.getContext("webgl");
GL2.init(ctx2);
GL2.setSize(window.innerWidth / 2, window.innerHeight);
console.log(GL);

/*
// log WebGL Context native methods
const regex = RegExp("[a-z]");
for (let s in GL.gl) {
  const firtChar = s.substring(0, 1);
  if (regex.test(firtChar)) {
    console.log(s);
  }
}
*/
document.body.appendChild(canvas1);
document.body.appendChild(canvas2);

const g = 0.1;
// GL.clear(1, 0, 0, g);
// GL2.clear(0, 1, 0, g);

GL.clear(g, 0, 0, 1);
GL2.clear(0, g, 0, 1);

const draw1 = true;
const shader = new GLShader();
console.log(shader);
const mesh = new Mesh();
console.log(mesh);

let s = 0.5;
// const positions = [[0, s, 0], [-s, -s / 2, 0], [s, -s / 2, 0]];
const positions = [
  vec3.fromValues(0, s, 0),
  vec3.fromValues(-s, -s / 2, 0),
  vec3.fromValues(s, -s / 2, 0),
];
// const colors = [[1, 0, 0], [0, 1, 0], [0, 0, 1]].flat();
const colors = [[1, 0, 0], [0, 1, 0], [0, 0, 1]];
const indices = [0, 1, 2];

mesh
  .bufferVertex(positions)
  .bufferData(colors, "aColor")
  .bufferIndex(indices);

// uniforms
shader.uniform("uColor", "vec3", [1, 0, 0]);

/*
shader.uniform('uScale', 0.5);
shader.uniform('uTranslate', [0.1, 0.1]);
*/

/*
 * Shader and Mesh ( buffers ) won't be created until they are going to be bind
 * They'll be generated by the WebGL context that it binds or draws
 */
if (draw1) {
  shader.bind();
  GL.draw(mesh);
} else {
  shader.bind(GL2);
  GL2.draw(mesh);
}

// resize
window.addEventListener("resize", resize);

function resize() {
  GL.setSize(window.innerWidth / 2, window.innerHeight);
  GL2.setSize(window.innerWidth / 2, window.innerHeight);
}
